version: '3.5'

services:
  nest_server_postgres:
    container_name: nest_server_postgres
    image: postgres:14
    environment:
      POSTGRES_USER: nest_server
      POSTGRES_PASSWORD: nest_server
      PGDATA: /data/postgres
    volumes:
       - postgres:/var/www/nest_server/docker-volumes/postgres
    ports:
      - 127.0.0.1:5432:5432
    networks:
      - nest_server
    restart: unless-stopped

  nest_server_pgadmin:
    container_name: nest_server_pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: nest_server@admin.com
      PGADMIN_DEFAULT_PASSWORD: nest_server
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
       - pgadmin:/var/www/nest_server/docker-volumes/pgadmin
    ports:
      - 127.0.0.1:5050:80
    networks:
      - nest_server
    restart: unless-stopped

networks:
  nest_server:
    driver: bridge

volumes:
  postgres:
  pgadmin: